### PR TITLE
Updated backend for user

### PR DESCRIPTION
**Pull request by KimjManansala**
I init the database and I created a migration for the User. I have also created a route for the user to register. Need to created front-end to allow user to create a user

### CODE REVIEW

**Comment by aarandela** [comment]
Whats up with your user model only having username? Isn't it supposed to have password as well?

**Comment by KimjManansala** [comment]
Hmm I just notice it has not password. The migration folder shows password tab and also in my database. I'll end it and then push again after I finish the Front-end

**Comment by aarandela** [comment]
You can add columns anyways on the models. I'm going to merge this so that we have sequelize to work with on our end.

**Comment by KimjManansala** [comment]
Okidokie

**Pull request merged**
